working_directory = "/home/waxer"

[colors.cursor]
cursor = "0xC00FD2"
text = "0xffffff"

[font]
size = 10

[font.normal]
family = "hack"
style = "Regular"

[font.offset]
x = -1

[[keyboard.bindings]]
action = "None"
key = "Left"
mods = "Control"

[[keyboard.bindings]]
action = "None"
key = "Right"
mods = "Control"

[scrolling]
history = 50000

[shell]
program = "/bin/zsh"

[window]
startup_mode = "Fullscreen"
